
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TENGAH
 */
public class Books_Logger extends javax.swing.JFrame {
      Connection conn = null;
      PreparedStatement pst = null;
      ResultSet rs = null;
    /**
     * Creates new form Books
     */
    public Books_Logger() {
        initComponents();
        ShowDate();
    }
    void ShowDate(){
        Date d = new Date();
           SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jTextField_Book_Log_Date.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Book_ISBN = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_Book_Accession_Number = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txt_Book_ISBN_number = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txt_Book_Name = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txt_Book_Author = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txt_Book_Edition = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel_back = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_Book_Log_Date = new javax.swing.JTextField();
        jLabel13_book_save_button = new javax.swing.JLabel();
        availability = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ISBN");

        txt_Book_ISBN.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_ISBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_ISBN.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN.setToolTipText("Book ISBN");
        txt_Book_ISBN.setBorder(null);
        txt_Book_ISBN.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_ISBN.setName(""); // NOI18N
        txt_Book_ISBN.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_ISBNActionPerformed(evt);
            }
        });
        txt_Book_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_ISBNKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booklog48.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Books Logger Window");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(141, 133, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accession Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 60, 154, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 180, 154, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ISBN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 120, 154, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Author");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 240, 154, 26));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 90, 500, 10));

        txt_Book_Accession_Number.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Accession_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Accession_Number.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Accession_Number.setBorder(null);
        txt_Book_Accession_Number.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Accession_Number.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Accession_Number.setName(""); // NOI18N
        txt_Book_Accession_Number.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Accession_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Accession_NumberActionPerformed(evt);
            }
        });
        txt_Book_Accession_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Accession_NumberKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Book_Accession_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 60, 500, 32));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 150, 500, 10));

        txt_Book_ISBN_number.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_ISBN_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_ISBN_number.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN_number.setBorder(null);
        txt_Book_ISBN_number.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN_number.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_ISBN_number.setName(""); // NOI18N
        txt_Book_ISBN_number.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_ISBN_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_ISBN_numberActionPerformed(evt);
            }
        });
        txt_Book_ISBN_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_ISBN_numberKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Book_ISBN_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 120, 500, 32));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 210, 500, 10));

        txt_Book_Name.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Name.setBorder(null);
        txt_Book_Name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Name.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Name.setName(""); // NOI18N
        txt_Book_Name.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_NameActionPerformed(evt);
            }
        });
        txt_Book_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_NameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Book_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 180, 500, 32));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 270, 500, 10));

        txt_Book_Author.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Author.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Author.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Author.setBorder(null);
        txt_Book_Author.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Author.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Author.setName(""); // NOI18N
        txt_Book_Author.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_AuthorActionPerformed(evt);
            }
        });
        txt_Book_Author.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_AuthorKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Book_Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 240, 500, 32));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 330, 500, 10));

        txt_Book_Edition.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Edition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Edition.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Edition.setBorder(null);
        txt_Book_Edition.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Edition.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Edition.setName(""); // NOI18N
        txt_Book_Edition.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_EditionActionPerformed(evt);
            }
        });
        txt_Book_Edition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_EditionKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Book_Edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 300, 500, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Edition");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 310, 154, 26));

        jPanel_back.setBackground(new java.awt.Color(141, 133, 133));
        jPanel_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_backMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_backLayout = new javax.swing.GroupLayout(jPanel_back);
        jPanel_back.setLayout(jPanel_backLayout);
        jPanel_backLayout.setHorizontalGroup(
            jPanel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_backLayout.setVerticalGroup(
            jPanel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_backLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 402, -1, -1));

        jPanel3.setBackground(new java.awt.Color(141, 133, 133));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 140, 40));

        jTextField_Book_Log_Date.setEditable(false);
        jTextField_Book_Log_Date.setBackground(new java.awt.Color(141, 133, 133));
        jTextField_Book_Log_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Book_Log_Date.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Book_Log_Date.setBorder(null);
        jTextField_Book_Log_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Book_Log_DateActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Book_Log_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 432, 137, 30));

        jLabel13_book_save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save48px.png"))); // NOI18N
        jLabel13_book_save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13_book_save_buttonMousePressed(evt);
            }
        });
        jPanel1.add(jLabel13_book_save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 50, 50));

        availability.setForeground(new java.awt.Color(141, 133, 133));
        availability.setText("Available");
        jPanel1.add(availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 414, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Book_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBNActionPerformed

    private void txt_Book_ISBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_ISBNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBNKeyPressed

    private void txt_Book_Accession_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Accession_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Accession_NumberActionPerformed

    private void txt_Book_Accession_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Accession_NumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Accession_NumberKeyPressed

    private void txt_Book_ISBN_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_ISBN_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBN_numberActionPerformed

    private void txt_Book_ISBN_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_ISBN_numberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBN_numberKeyPressed

    private void txt_Book_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_NameActionPerformed

    private void txt_Book_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_NameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_NameKeyPressed

    private void txt_Book_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_AuthorActionPerformed

    private void txt_Book_AuthorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_AuthorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_AuthorKeyPressed

    private void txt_Book_EditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_EditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_EditionActionPerformed

    private void txt_Book_EditionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_EditionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_EditionKeyPressed

    private void jPanel_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_backMousePressed
        // TODO add your handling code here:
        new Books_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel_backMousePressed

    private void jTextField_Book_Log_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Book_Log_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Book_Log_DateActionPerformed

    private void jLabel13_book_save_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13_book_save_buttonMousePressed
        // TODO add your handling code here:
        if((txt_Book_Accession_Number.getText().trim().isEmpty()) || (txt_Book_ISBN_number.getText().trim().isEmpty()) || (txt_Book_Name.getText().trim().isEmpty())|| (txt_Book_Author.getText().trim().isEmpty()) ){
            JOptionPane.showMessageDialog(this, "Empty fields found, fill in.", "Warning", 2);
        }else{
        try{
            String sql3 = "INSERT INTO `books`(`Accession_Number`, `ISBN`, `Name`, `Author`, `Edition`, `Date_In`, `Status`) VALUES ( ?, ?, ?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(sql3);
            pst.setString(1, txt_Book_Accession_Number.getText());
            pst.setString(2, txt_Book_ISBN_number.getText());
            pst.setString(3, txt_Book_Name.getText());
            pst.setString(4, txt_Book_Author.getText());
            pst.setString(5, txt_Book_Edition.getText());
            pst.setString(6, jTextField_Book_Log_Date.getText());
            pst.setString(7, availability.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Book Log Successfull");
            txt_Book_Accession_Number.setText("");
            txt_Book_ISBN_number.setText("");
            txt_Book_Name.setText("");
            txt_Book_Author.setText("");
            txt_Book_Edition.setText("");  
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Accession number specified is currently in use", "Error", 0);
        }
        }
        /*txt_Book_Accession_Number.setText("");
        txt_Book_ISBN_number.setText("");
        txt_Book_Name.setText("");
        txt_Book_Author.setText("");
        txt_Book_Edition.setText("");*/              
    }//GEN-LAST:event_jLabel13_book_save_buttonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books_Logger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books_Logger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books_Logger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books_Logger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books_Logger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availability;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13_book_save_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_back;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField_Book_Log_Date;
    private javax.swing.JTextField txt_Book_Accession_Number;
    private javax.swing.JTextField txt_Book_Author;
    private javax.swing.JTextField txt_Book_Edition;
    private javax.swing.JTextField txt_Book_ISBN;
    private javax.swing.JTextField txt_Book_ISBN_number;
    private javax.swing.JTextField txt_Book_Name;
    // End of variables declaration//GEN-END:variables
}
