
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TENGAH
 */
public class Code_Update_window extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Code_Update_window
     */
    public Code_Update_window() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_New_Code = new javax.swing.JPasswordField();
        jLabel3_update_code = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Current_Code = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Code_Shield_Number = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel_code_check = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Super Code Update Centre");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(141, 133, 133));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Code");

        txt_New_Code.setBackground(new java.awt.Color(141, 133, 133));
        txt_New_Code.setForeground(new java.awt.Color(255, 255, 255));
        txt_New_Code.setToolTipText("Enter your preffered new code");
        txt_New_Code.setAlignmentX(0.0F);
        txt_New_Code.setAlignmentY(0.0F);
        txt_New_Code.setBorder(null);
        txt_New_Code.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_New_Code.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_New_Code.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_New_Code.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_New_Code.setSelectionStart(2);
        txt_New_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_New_CodeKeyPressed(evt);
            }
        });

        jLabel3_update_code.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update48.png"))); // NOI18N
        jLabel3_update_code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3_update_codeMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Current Code");

        txt_Current_Code.setEditable(false);
        txt_Current_Code.setBackground(new java.awt.Color(141, 133, 133));
        txt_Current_Code.setForeground(new java.awt.Color(255, 255, 255));
        txt_Current_Code.setAlignmentX(0.0F);
        txt_Current_Code.setAlignmentY(0.0F);
        txt_Current_Code.setBorder(null);
        txt_Current_Code.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Current_Code.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Current_Code.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_Current_Code.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Current_Code.setSelectionStart(2);
        txt_Current_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Current_CodeKeyPressed(evt);
            }
        });

        txt_Code_Shield_Number.setBackground(new java.awt.Color(141, 133, 133));
        txt_Code_Shield_Number.setForeground(new java.awt.Color(255, 255, 255));
        txt_Code_Shield_Number.setToolTipText("The current code");
        txt_Code_Shield_Number.setAlignmentX(0.0F);
        txt_Code_Shield_Number.setAlignmentY(0.0F);
        txt_Code_Shield_Number.setBorder(null);
        txt_Code_Shield_Number.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Code_Shield_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Code_Shield_Number.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_Code_Shield_Number.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Code_Shield_Number.setSelectionStart(2);
        txt_Code_Shield_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Code_Shield_NumberKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Code Shield Number");

        jLabel_code_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_code_check32.png"))); // NOI18N
        jLabel_code_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_code_checkMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter code shield number to retrieve current code.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3_update_code, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Current_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_New_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Code_Shield_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_code_check, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_Code_Shield_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_code_check, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(txt_Current_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txt_New_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3_update_code)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_New_CodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_New_CodeKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isISOControl(c) || Character.isLowerCase(c) || Character.isUpperCase(c)) {
            txt_New_Code.setEditable(true);
        } else {
            txt_New_Code.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_New_CodeKeyPressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Operation will be terminated", "Warning", 2,
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_CANCEL_OPTION) {

        } else {
            dispose();
            new Settings_window().setVisible(true);
        }


    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3_update_codeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_update_codeMousePressed
        // TODO add your handling code here:

        try {
            String code_update = "UPDATE `super_code` SET `New_Code` = ? WHERE `Current_Code` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(code_update);
            pst.setString(2, txt_Current_Code.getText());
            pst.setString(1, txt_New_Code.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Code update successfull");
            txt_Code_Shield_Number.setText("");
            txt_Current_Code.setText("");
            txt_New_Code.setText("");
           new Settings_window().setVisible(true);
           dispose();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error occured while updating code");
        }
    }//GEN-LAST:event_jLabel3_update_codeMousePressed

    private void txt_Current_CodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Current_CodeKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isISOControl(c) || Character.isLowerCase(c) || Character.isUpperCase(c)) {
            txt_Current_Code.setEditable(true);
        } else {
            txt_Current_Code.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_Current_CodeKeyPressed

    private void txt_Code_Shield_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Code_Shield_NumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Code_Shield_NumberKeyPressed

    private void jLabel_code_checkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_code_checkMousePressed
        // TODO add your handling code here:
         try {
            String query = "SELECT `Current_Code` FROM `super_code` WHERE `Code_Shield_Number` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_Code_Shield_Number.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String setCurrent_Code = rs.getString("Current_Code");
                txt_Current_Code.setText(setCurrent_Code);
                jLabel_code_check.setVisible(false);
            } else {
            JOptionPane.showMessageDialog(this, "Code Shield not found?");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Null");
        }
    }//GEN-LAST:event_jLabel_code_checkMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Code_Update_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Code_Update_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Code_Update_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Code_Update_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Code_Update_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_update_code;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_code_check;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField txt_Code_Shield_Number;
    private javax.swing.JPasswordField txt_Current_Code;
    private javax.swing.JPasswordField txt_New_Code;
    // End of variables declaration//GEN-END:variables
}
