
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TENGAH
 */
public class Issue_Book_window extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Issue_Book_window
     */
    public Issue_Book_window() {
        initComponents();
        // conn = Sql_Connect.Connectdb();
        txt_Student_Name.setEditable(false);
        txt_Student_Surname.setEditable(false);
        txt_Student_ID.setEditable(false);
        txt_Student_Gender.setEditable(false);
        txt_Student_Course.setEditable(false);
        txt_Student_Level.setEditable(false);
        txt_Student_Intake.setEditable(false);
        txt_Student_Intake_Year.setEditable(false);
        jLabel9_Book_Search_Enable.setVisible(false);
        jLabel9_Student_Search_Enable.setVisible(false);
        /*-----------------------------------------------*/
        txt_Book_ISBN.setEditable(false);
        txt_Book_Name.setEditable(false);
        txt_Book_Author.setEditable(false);
        txt_Book_Edition.setEditable(false);
        ShowDate();
    }

    void ShowDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jLabel_Issue_Date.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_Book_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_Book_Author = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_Book_ISBN = new javax.swing.JTextField();
        issue_book_button = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Issue_Back_Button = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Book_Edition = new javax.swing.JTextField();
        jComboBox_condition = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txt_Student_Name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField_Issue_book_search_by_acc_number = new javax.swing.JTextField();
        jLabel9_Book_search_button = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField_Issue_student_search_by_Reg_Number = new javax.swing.JTextField();
        jLabel9_Student_search_button = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txt_Student_Gender = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        txt_Student_ID = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txt_Student_Course = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txt_Student_Level = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        txt_Student_Intake = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        txt_Student_Intake_Year = new javax.swing.JTextField();
        jLabel_Issue_Date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser_Return_Date = new com.toedter.calendar.JDateChooser();
        jSeparator15 = new javax.swing.JSeparator();
        txt_Student_Surname = new javax.swing.JTextField();
        jLabel9_Book_Search_Enable = new javax.swing.JLabel();
        jLabel9_Student_Search_Enable = new javax.swing.JLabel();
        check_book_status = new javax.swing.JLabel();
        check_student_status = new javax.swing.JLabel();
        book_status = new javax.swing.JLabel();
        student_status = new javax.swing.JLabel();
        days_spent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setPreferredSize(new java.awt.Dimension(843, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Issue Book Window");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, 210, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_issue48.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, 70));

        jPanel2.setBackground(new java.awt.Color(141, 133, 133));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ISBN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 125, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 183, 110, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(140, 213, 350, 10);

        txt_Book_Name.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Name.setToolTipText("Book name");
        txt_Book_Name.setBorder(null);
        txt_Book_Name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Name.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Name.setName(""); // NOI18N
        txt_Book_Name.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_NameActionPerformed(evt);
            }
        });
        txt_Book_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_NameKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Book_Name);
        txt_Book_Name.setBounds(140, 183, 350, 32);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 240, 100, 30);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(140, 271, 350, 10);

        txt_Book_Author.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Author.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Author.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Author.setToolTipText("Book Author");
        txt_Book_Author.setBorder(null);
        txt_Book_Author.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Author.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Author.setName(""); // NOI18N
        txt_Book_Author.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_AuthorActionPerformed(evt);
            }
        });
        txt_Book_Author.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_AuthorKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Book_Author);
        txt_Book_Author.setBounds(140, 241, 350, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edition");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 299, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Condition");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 368, 100, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(140, 155, 350, 10);

        txt_Book_ISBN.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_ISBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_ISBN.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN.setToolTipText("Book ISBN");
        txt_Book_ISBN.setBorder(null);
        txt_Book_ISBN.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_ISBN.setName(""); // NOI18N
        txt_Book_ISBN.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_ISBNActionPerformed(evt);
            }
        });
        txt_Book_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_ISBNKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Book_ISBN);
        txt_Book_ISBN.setBounds(140, 125, 350, 32);

        issue_book_button.setBackground(new java.awt.Color(118, 150, 166));
        issue_book_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issue_book_button.setName(""); // NOI18N
        issue_book_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                issue_book_buttonMousePressed(evt);
            }
        });
        issue_book_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Issue Book");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        issue_book_button.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 20));

        jPanel2.add(issue_book_button);
        issue_book_button.setBounds(460, 600, 160, 40);

        jLabel_Issue_Back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N
        jLabel_Issue_Back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_Issue_Back_ButtonMousePressed(evt);
            }
        });
        jPanel2.add(jLabel_Issue_Back_Button);
        jLabel_Issue_Back_Button.setBounds(1050, 590, 60, 50);
        jPanel2.add(jSeparator9);
        jSeparator9.setBounds(140, 329, 350, 10);

        txt_Book_Edition.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Edition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Edition.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Edition.setToolTipText("Book edition/version");
        txt_Book_Edition.setBorder(null);
        txt_Book_Edition.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Edition.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Edition.setName(""); // NOI18N
        txt_Book_Edition.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_EditionActionPerformed(evt);
            }
        });
        txt_Book_Edition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_EditionKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Book_Edition);
        txt_Book_Edition.setBounds(140, 299, 350, 32);

        jComboBox_condition.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox_condition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_condition.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "No torn pages", "Good", "Torn" }));
        jPanel2.add(jComboBox_condition);
        jComboBox_condition.setBounds(140, 369, 260, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Surname");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(560, 180, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(560, 240, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Level");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(560, 420, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(558, 115, 100, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ID");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(560, 300, 100, 30);
        jPanel2.add(jSeparator11);
        jSeparator11.setBounds(688, 145, 360, 10);

        txt_Student_Name.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Name.setToolTipText("Student Name");
        txt_Student_Name.setBorder(null);
        txt_Student_Name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Name.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Name.setName(""); // NOI18N
        txt_Student_Name.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_NameActionPerformed(evt);
            }
        });
        txt_Student_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_NameKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Name);
        txt_Student_Name.setBounds(688, 116, 360, 32);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(530, 10, 10, 570);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Borrower Details here.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(558, 10, 170, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Books Details here.");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 10, 140, 20);
        jPanel2.add(jSeparator14);
        jSeparator14.setBounds(230, 100, 260, 10);

        jTextField_Issue_book_search_by_acc_number.setBackground(new java.awt.Color(141, 133, 133));
        jTextField_Issue_book_search_by_acc_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Issue_book_search_by_acc_number.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Issue_book_search_by_acc_number.setToolTipText("Enter book's accession number");
        jTextField_Issue_book_search_by_acc_number.setBorder(null);
        jTextField_Issue_book_search_by_acc_number.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField_Issue_book_search_by_acc_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Issue_book_search_by_acc_numberActionPerformed(evt);
            }
        });
        jTextField_Issue_book_search_by_acc_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Issue_book_search_by_acc_numberKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField_Issue_book_search_by_acc_number);
        jTextField_Issue_book_search_by_acc_number.setBounds(230, 70, 260, 40);

        jLabel9_Book_search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search32.png"))); // NOI18N
        jLabel9_Book_search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9_Book_search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9_Book_search_buttonMousePressed(evt);
            }
        });
        jPanel2.add(jLabel9_Book_search_button);
        jLabel9_Book_search_button.setBounds(190, 70, 30, 32);
        jPanel2.add(jSeparator13);
        jSeparator13.setBounds(790, 90, 260, 10);

        jTextField_Issue_student_search_by_Reg_Number.setBackground(new java.awt.Color(141, 133, 133));
        jTextField_Issue_student_search_by_Reg_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Issue_student_search_by_Reg_Number.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Issue_student_search_by_Reg_Number.setToolTipText("Enter student Reg number");
        jTextField_Issue_student_search_by_Reg_Number.setBorder(null);
        jTextField_Issue_student_search_by_Reg_Number.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField_Issue_student_search_by_Reg_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Issue_student_search_by_Reg_NumberActionPerformed(evt);
            }
        });
        jTextField_Issue_student_search_by_Reg_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Issue_student_search_by_Reg_NumberKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField_Issue_student_search_by_Reg_Number);
        jTextField_Issue_student_search_by_Reg_Number.setBounds(790, 60, 260, 40);

        jLabel9_Student_search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search32.png"))); // NOI18N
        jLabel9_Student_search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9_Student_search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9_Student_search_buttonMousePressed(evt);
            }
        });
        jPanel2.add(jLabel9_Student_search_button);
        jLabel9_Student_search_button.setBounds(760, 60, 32, 32);
        jPanel2.add(jSeparator12);
        jSeparator12.setBounds(690, 270, 360, 10);

        txt_Student_Gender.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Gender.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Gender.setToolTipText("Student Gender");
        txt_Student_Gender.setBorder(null);
        txt_Student_Gender.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Gender.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Gender.setName(""); // NOI18N
        txt_Student_Gender.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_GenderActionPerformed(evt);
            }
        });
        txt_Student_Gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_GenderKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Gender);
        txt_Student_Gender.setBounds(690, 240, 360, 32);
        jPanel2.add(jSeparator16);
        jSeparator16.setBounds(690, 330, 360, 10);

        txt_Student_ID.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_ID.setToolTipText("Student ID Number");
        txt_Student_ID.setBorder(null);
        txt_Student_ID.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_ID.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_ID.setName(""); // NOI18N
        txt_Student_ID.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_IDActionPerformed(evt);
            }
        });
        txt_Student_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_IDKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_ID);
        txt_Student_ID.setBounds(690, 300, 360, 32);
        jPanel2.add(jSeparator17);
        jSeparator17.setBounds(690, 390, 360, 10);

        txt_Student_Course.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Course.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Course.setToolTipText("Student Course");
        txt_Student_Course.setBorder(null);
        txt_Student_Course.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Course.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Course.setName(""); // NOI18N
        txt_Student_Course.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_CourseActionPerformed(evt);
            }
        });
        txt_Student_Course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_CourseKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Course);
        txt_Student_Course.setBounds(690, 360, 360, 32);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Course");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(560, 360, 100, 30);
        jPanel2.add(jSeparator18);
        jSeparator18.setBounds(690, 450, 360, 10);

        txt_Student_Level.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Level.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Level.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Level.setToolTipText("Student Level");
        txt_Student_Level.setBorder(null);
        txt_Student_Level.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Level.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Level.setName(""); // NOI18N
        txt_Student_Level.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_LevelActionPerformed(evt);
            }
        });
        txt_Student_Level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_LevelKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Level);
        txt_Student_Level.setBounds(690, 420, 360, 32);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Intake Year");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(560, 540, 100, 30);
        jPanel2.add(jSeparator19);
        jSeparator19.setBounds(690, 510, 360, 10);

        txt_Student_Intake.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Intake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Intake.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Intake.setToolTipText("Student Intake");
        txt_Student_Intake.setBorder(null);
        txt_Student_Intake.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Intake.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Intake.setName(""); // NOI18N
        txt_Student_Intake.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Intake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_IntakeActionPerformed(evt);
            }
        });
        txt_Student_Intake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_IntakeKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Intake);
        txt_Student_Intake.setBounds(690, 480, 360, 32);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Intake");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(560, 480, 100, 30);
        jPanel2.add(jSeparator20);
        jSeparator20.setBounds(690, 570, 360, 10);

        txt_Student_Intake_Year.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Intake_Year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Intake_Year.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Intake_Year.setToolTipText("Student Intake Year");
        txt_Student_Intake_Year.setBorder(null);
        txt_Student_Intake_Year.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Intake_Year.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Intake_Year.setName(""); // NOI18N
        txt_Student_Intake_Year.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Intake_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_Intake_YearActionPerformed(evt);
            }
        });
        txt_Student_Intake_Year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_Intake_YearKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Intake_Year);
        txt_Student_Intake_Year.setBounds(690, 540, 360, 32);

        jLabel_Issue_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Issue_Date.setForeground(new java.awt.Color(141, 133, 133));
        jPanel2.add(jLabel_Issue_Date);
        jLabel_Issue_Date.setBounds(20, 610, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Return Date");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 440, 100, 30);
        jPanel2.add(jDateChooser_Return_Date);
        jDateChooser_Return_Date.setBounds(140, 440, 140, 30);
        jPanel2.add(jSeparator15);
        jSeparator15.setBounds(690, 210, 360, 10);

        txt_Student_Surname.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Surname.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Surname.setToolTipText("Student Surname");
        txt_Student_Surname.setBorder(null);
        txt_Student_Surname.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Surname.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Surname.setName(""); // NOI18N
        txt_Student_Surname.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_SurnameActionPerformed(evt);
            }
        });
        txt_Student_Surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_SurnameKeyPressed(evt);
            }
        });
        jPanel2.add(txt_Student_Surname);
        txt_Student_Surname.setBounds(690, 180, 360, 32);

        jLabel9_Book_Search_Enable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enable_tickC32.png"))); // NOI18N
        jLabel9_Book_Search_Enable.setToolTipText("Enable search");
        jLabel9_Book_Search_Enable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9_Book_Search_Enable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9_Book_Search_EnableMousePressed(evt);
            }
        });
        jPanel2.add(jLabel9_Book_Search_Enable);
        jLabel9_Book_Search_Enable.setBounds(490, 70, 32, 32);

        jLabel9_Student_Search_Enable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enable_tickC32.png"))); // NOI18N
        jLabel9_Student_Search_Enable.setToolTipText("Enable search");
        jLabel9_Student_Search_Enable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9_Student_Search_Enable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9_Student_Search_EnableMousePressed(evt);
            }
        });
        jPanel2.add(jLabel9_Student_Search_Enable);
        jLabel9_Student_Search_Enable.setBounds(1050, 60, 32, 32);

        check_book_status.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        check_book_status.setForeground(new java.awt.Color(255, 255, 255));
        check_book_status.setText("Check Status");
        check_book_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_book_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                check_book_statusMousePressed(evt);
            }
        });
        jPanel2.add(check_book_status);
        check_book_status.setBounds(430, 10, 90, 20);

        check_student_status.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        check_student_status.setForeground(new java.awt.Color(255, 255, 255));
        check_student_status.setText("Check Status");
        check_student_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_student_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                check_student_statusMousePressed(evt);
            }
        });
        jPanel2.add(check_student_status);
        check_student_status.setBounds(1010, 10, 100, 20);

        book_status.setForeground(new java.awt.Color(141, 133, 133));
        book_status.setText("Not Available");
        jPanel2.add(book_status);
        book_status.setBounds(150, 610, 110, 30);

        student_status.setForeground(new java.awt.Color(141, 133, 133));
        student_status.setText("Outstanding book");
        jPanel2.add(student_status);
        student_status.setBounds(290, 610, 90, 30);
        jPanel2.add(days_spent);
        days_spent.setBounds(50, 520, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Student_CourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_CourseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_CourseKeyPressed

    private void txt_Student_CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_CourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_CourseActionPerformed

    private void txt_Student_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_IDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_IDKeyPressed

    private void txt_Student_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_IDActionPerformed

    private void txt_Student_GenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_GenderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_GenderKeyPressed

    private void txt_Student_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_GenderActionPerformed

    private void jLabel9_Student_search_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9_Student_search_buttonMousePressed
        // TODO add your handling code here:
        if(jTextField_Issue_student_search_by_Reg_Number.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Null value, can't find borrower!");
        }else{
        try {
            String query = "SELECT * FROM `students` WHERE `Reg No` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, jTextField_Issue_student_search_by_Reg_Number.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                /*txt_Student_Name.setEditable(true);
                txt_Student_Surname.setEditable(true);
                txt_Student_ID.setEditable(true);
                txt_Student_Gender.setEditable(true);
                txt_Student_Course.setEditable(true);
                txt_Student_Level.setEditable(true);
                txt_Student_Intake.setEditable(true);
                txt_Student_Intake_Year.setEditable(true);*/
                jTextField_Issue_student_search_by_Reg_Number.setEditable(false);
                jLabel9_Student_Search_Enable.setVisible(true);
                /*---------------------------------------------------*/
                String setStudent_name = rs.getString("Name");
                txt_Student_Name.setText(setStudent_name);

                String setStudent_surname = rs.getString("Surname");
                txt_Student_Surname.setText(setStudent_surname);

                String setStudent_ID = rs.getString("National_ID");
                txt_Student_ID.setText(setStudent_ID);

                String setStudent_gender = rs.getString("Gender");
                txt_Student_Gender.setText(setStudent_gender);

                String setCourse = rs.getString("Course");
                txt_Student_Course.setText(setCourse);

                String setStudent_level = rs.getString("Level");
                txt_Student_Level.setText(setStudent_level);

                String setIntake = rs.getString("Intake");
                txt_Student_Intake.setText(setIntake);

                String setIntake_Year = rs.getString("Intake_Year");
                txt_Student_Intake_Year.setText(setIntake_Year);
            } else {
                JOptionPane.showMessageDialog(this, "Borrower not found, check your syntax!");
                txt_Student_Name.setText("");
                txt_Student_Surname.setText("");
                txt_Student_ID.setText("");
                txt_Student_Gender.setText("");
                txt_Student_Course.setText("");
                txt_Student_Level.setText("");
                txt_Student_Intake.setText("");
                txt_Student_Intake_Year.setText("");
                jTextField_Issue_student_search_by_Reg_Number.setText("");
                /*-------------------------------------------*/
                txt_Student_Name.setEditable(false);
                txt_Student_Surname.setEditable(false);
                txt_Student_ID.setEditable(false);
                txt_Student_Gender.setEditable(false);
                txt_Student_Course.setEditable(false);
                txt_Student_Level.setEditable(false);
                txt_Student_Intake.setEditable(false);
                txt_Student_Intake_Year.setEditable(false);
            }
        } catch (Exception ex) {
        }
        }
    }//GEN-LAST:event_jLabel9_Student_search_buttonMousePressed

    private void jTextField_Issue_student_search_by_Reg_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Issue_student_search_by_Reg_NumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Issue_student_search_by_Reg_NumberKeyReleased

    private void jTextField_Issue_student_search_by_Reg_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Issue_student_search_by_Reg_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Issue_student_search_by_Reg_NumberActionPerformed

    private void jLabel9_Book_search_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9_Book_search_buttonMousePressed
        // TODO add your handling code here:
        if (jTextField_Issue_book_search_by_acc_number.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Null value, can't find book!");
        }else{
        try {
            String query = "SELECT * FROM `books` WHERE `Accession_Number` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, jTextField_Issue_book_search_by_acc_number.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                // txt_Book_ISBN.setEditable(true);
                // txt_Book_Name.setEditable(true);
                // txt_Book_Author.setEditable(true);
                // txt_Book_Edition.setEditable(true);
                //jTextField_Update_book_search_by_acc_number.setText("");
                jTextField_Issue_book_search_by_acc_number.setEditable(false);
                jLabel9_Book_Search_Enable.setVisible(true);

                String setBook_ISBN = rs.getString("ISBN");
                txt_Book_ISBN.setText(setBook_ISBN);

                String setBook_Name = rs.getString("Name");
                txt_Book_Name.setText(setBook_Name);

                String setBook_Author = rs.getString("Author");
                txt_Book_Author.setText(setBook_Author);

                String setBook_Edition = rs.getString("Edition");
                txt_Book_Edition.setText(setBook_Edition);

                // txt_Date_Logged_In_Update.setText(setDate);
            } else {
                JOptionPane.showMessageDialog(this, "Book not found, check your syntax!");
                txt_Book_ISBN.setText("");
                txt_Book_Name.setText("");
                txt_Book_Author.setText("");
                txt_Book_Edition.setText("");

                jTextField_Issue_book_search_by_acc_number.setText("");
                // txt_Date_Logged_In_Update.setText("");
                txt_Book_ISBN.setEditable(false);
                txt_Book_Name.setEditable(false);
                txt_Book_Author.setEditable(false);
                txt_Book_Edition.setEditable(false);
                //jDateChooser1_Update.setEnabled(false);
            }
        } catch (Exception ex) {
        }
        }
    }//GEN-LAST:event_jLabel9_Book_search_buttonMousePressed

    private void jTextField_Issue_book_search_by_acc_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Issue_book_search_by_acc_numberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Issue_book_search_by_acc_numberKeyReleased

    private void jTextField_Issue_book_search_by_acc_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Issue_book_search_by_acc_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Issue_book_search_by_acc_numberActionPerformed

    private void txt_Student_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_NameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_NameKeyPressed

    private void txt_Student_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_NameActionPerformed

    private void txt_Book_EditionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_EditionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_EditionKeyPressed

    private void txt_Book_EditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_EditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_EditionActionPerformed

    private void jLabel_Issue_Back_ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Issue_Back_ButtonMousePressed
        // TODO add your handling code here:
        new Books_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel_Issue_Back_ButtonMousePressed

    private void issue_book_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_book_buttonMousePressed
        // TODO add your handling code here:
        /* if ((txt_Signup_name.getText().trim().isEmpty()) && (txt_Signup_ID.getText().trim().isEmpty()) && (txt_Signup_code.getText().trim().isEmpty()) && (txt_signup_password.getText().trim().isEmpty()) && (txt_signup_confirm_password.getText().trim().isEmpty())) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No input data found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        } else if ((txt_Signup_name.getText().trim().isEmpty()) || (txt_Signup_ID.getText().trim().isEmpty()) || (txt_Signup_code.getText().trim().isEmpty()) || (txt_signup_password.getText().trim().isEmpty()) || (txt_signup_confirm_password.getText().trim().isEmpty())) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Empty fields found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        }*/
 /* try{
            String sql = "INSERT INTO `issue_book`() VALUES (?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(sql);

            pst.executeUpdate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Issue on students");
        }*/
        try {
            java.sql.Date return_date = new java.sql.Date(jDateChooser_Return_Date.getDate().getTime());
            String query1 = "INSERT INTO `issue_book`(`Book_Accession_Number`, `Book_ISBN`, `Book_Name`, `Book_Author`, `Book_Edition`, `Book_Condition`, `Student_Reg_No`, `Student_Name`, `Student_Surname`, `Student_Gender`, `Student_ID`, `_Course`, `_Level`, `Student_Intake`, `Student_Intake_Year`, `Issue_Date`, `Days_Spent`, `Return_Date`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,'" + return_date + "')";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query1);
            pst.setString(1, jTextField_Issue_book_search_by_acc_number.getText());
            pst.setString(2, txt_Book_ISBN.getText());
            pst.setString(3, txt_Book_Name.getText());
            pst.setString(4, txt_Book_Author.getText());
            pst.setString(5, txt_Book_Edition.getText());
            pst.setString(6, (String) jComboBox_condition.getSelectedItem());
            /*----------------------------------------------------------------------*/
            pst.setString(7, jTextField_Issue_student_search_by_Reg_Number.getText());
            pst.setString(8, txt_Student_Name.getText());
            pst.setString(9, txt_Student_Surname.getText());
            pst.setString(10, txt_Student_Gender.getText());
            pst.setString(11, txt_Student_ID.getText());
            pst.setString(12, txt_Student_Course.getText());
            pst.setString(13, txt_Student_Level.getText());
            pst.setString(14, txt_Student_Intake.getText());
            pst.setString(15, txt_Student_Intake_Year.getText());
            pst.setString(16, jLabel_Issue_Date.getText());
            pst.setString(17, days_spent.getText());
            pst.executeUpdate();
            
            /*---BORROW BOOK PROCESS----------------------taking id of book searched to be borrowed-*/
          try {
                String query2 = "UPDATE `books` SET `Status` =? WHERE `Accession_Number` = ?";
                conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
                pst = conn.prepareStatement(query2);
                pst.setString(2, jTextField_Issue_book_search_by_acc_number.getText());
                pst.setString(1, book_status.getText());
                pst.executeUpdate();
               //JOptionPane.showMessageDialog(this, "Book was given status");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            /*----BORROW BOOK PROCESS-----------ends here----------------------*/
            
            
            /*---BORROW BOOK PROCESS2---taking id of student searched to borrow the book--*/
            try {
                String query3 = "UPDATE `students` SET `Status` = ? WHERE `Reg No` = ?";
                conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
                pst = conn.prepareStatement(query3);
                pst.setString(2, jTextField_Issue_student_search_by_Reg_Number.getText());
                pst.setString(1, student_status.getText());
                pst.executeUpdate();
               // JOptionPane.showMessageDialog(this, "Student was given status");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
            /*----BORROW BOOK PROCESS2-----------ends here----------------------*/
            JOptionPane.showMessageDialog(this, "Book Borrowing Successfull");
            jTextField_Issue_book_search_by_acc_number.setText("");
            txt_Book_ISBN.setText("");
            txt_Book_Name.setText("");
            txt_Book_Author.setText("");
            txt_Book_Edition.setText("");
            /*----------------------------------------------------------------------*/
            jTextField_Issue_student_search_by_Reg_Number.setText("");
            txt_Student_Name.setText("");
            txt_Student_Surname.setText("");
            txt_Student_Gender.setText("");
            txt_Student_ID.setText("");
            txt_Student_Course.setText("");
            txt_Student_Level.setText("");
            txt_Student_Intake.setText("");
            txt_Student_Intake_Year.setText("");
            /*----------------------------------------------------------------------*/
            jTextField_Issue_student_search_by_Reg_Number.setEditable(true);
            jTextField_Issue_book_search_by_acc_number.setEditable(true);
            jLabel9_Book_Search_Enable.setVisible(false);
            jLabel9_Student_Search_Enable.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Process Failed");
        }

    }//GEN-LAST:event_issue_book_buttonMousePressed

    private void txt_Book_ISBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_ISBNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBNKeyPressed

    private void txt_Book_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBNActionPerformed

    private void txt_Book_AuthorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_AuthorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_AuthorKeyPressed

    private void txt_Book_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_AuthorActionPerformed

    private void txt_Book_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_NameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_NameKeyPressed

    private void txt_Book_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_NameActionPerformed

    private void txt_Student_LevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_LevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_LevelActionPerformed

    private void txt_Student_LevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_LevelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_LevelKeyPressed

    private void txt_Student_IntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_IntakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_IntakeActionPerformed

    private void txt_Student_IntakeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_IntakeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_IntakeKeyPressed

    private void txt_Student_Intake_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_Intake_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Intake_YearActionPerformed

    private void txt_Student_Intake_YearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_Intake_YearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Intake_YearKeyPressed

    private void txt_Student_SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_SurnameActionPerformed

    private void txt_Student_SurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_SurnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_SurnameKeyPressed

    private void jLabel9_Book_Search_EnableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9_Book_Search_EnableMousePressed
        // TODO add your handling code here:
        jTextField_Issue_book_search_by_acc_number.setEditable(true);
        jLabel9_Book_Search_Enable.setVisible(false);
        /*-------------------------------------*/
        txt_Book_ISBN.setText("");
        txt_Book_Name.setText("");
        txt_Book_Author.setText("");
        txt_Book_Edition.setText("");
        jTextField_Issue_book_search_by_acc_number.setText("");
        /*-----------------------------------*/
        //txt_Book_ISBN.setEditable(false);
        //txt_Book_Name.setEditable(false);
        //txt_Book_Author.setEditable(false);
        //txt_Book_Edition.setEditable(false);
        //jLabel9_Book_Search_Enable.setVisible(false);
        /*-----------------------------------*/
    }//GEN-LAST:event_jLabel9_Book_Search_EnableMousePressed

    private void jLabel9_Student_Search_EnableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9_Student_Search_EnableMousePressed
        // TODO add your handling code here:
        jTextField_Issue_student_search_by_Reg_Number.setEditable(true);
        jLabel9_Student_Search_Enable.setVisible(false);
        /*-------------------------------------*/
        txt_Student_Name.setText("");
        txt_Student_Surname.setText("");
        txt_Student_Gender.setText("");
        txt_Student_ID.setText("");
        txt_Student_Course.setText("");
        txt_Student_Level.setText("");
        txt_Student_Intake.setText("");
        txt_Student_Intake_Year.setText("");
        jTextField_Issue_student_search_by_Reg_Number.setText("");
        /*-----------------------------------*/
 /* txt_Book_Update_ISBN.setEditable(false);
        txt_Book_Update_Name.setEditable(false);
        txt_Book_Update_Author.setEditable(false);
        txt_Book_Update_Edition.setEditable(false);
        jLabel9_Book_Search_Enable.setVisible(false);
        -----------------------------------*/
    }//GEN-LAST:event_jLabel9_Student_Search_EnableMousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void check_book_statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_book_statusMousePressed
        // TODO add your handling code here:
        new Book_Check_window().setVisible(true);
        //check_student_status.setVisible(false);
        //check_book_status.setVisible(false);
    }//GEN-LAST:event_check_book_statusMousePressed

    private void check_student_statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_student_statusMousePressed
        // TODO add your handling code here:
        new Student_Check_window().setVisible(true);
        //check_book_status.setVisible(false);
        //check_student_status.setVisible(false);
    }//GEN-LAST:event_check_student_statusMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_Book_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_status;
    private javax.swing.JLabel check_book_status;
    private javax.swing.JLabel check_student_status;
    private javax.swing.JLabel days_spent;
    private javax.swing.JPanel issue_book_button;
    private javax.swing.JComboBox<String> jComboBox_condition;
    private com.toedter.calendar.JDateChooser jDateChooser_Return_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9_Book_Search_Enable;
    private javax.swing.JLabel jLabel9_Book_search_button;
    private javax.swing.JLabel jLabel9_Student_Search_Enable;
    private javax.swing.JLabel jLabel9_Student_search_button;
    private javax.swing.JLabel jLabel_Issue_Back_Button;
    private javax.swing.JLabel jLabel_Issue_Date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField_Issue_book_search_by_acc_number;
    private javax.swing.JTextField jTextField_Issue_student_search_by_Reg_Number;
    private javax.swing.JLabel student_status;
    private javax.swing.JTextField txt_Book_Author;
    private javax.swing.JTextField txt_Book_Edition;
    private javax.swing.JTextField txt_Book_ISBN;
    private javax.swing.JTextField txt_Book_Name;
    private javax.swing.JTextField txt_Student_Course;
    private javax.swing.JTextField txt_Student_Gender;
    private javax.swing.JTextField txt_Student_ID;
    private javax.swing.JTextField txt_Student_Intake;
    private javax.swing.JTextField txt_Student_Intake_Year;
    private javax.swing.JTextField txt_Student_Level;
    private javax.swing.JTextField txt_Student_Name;
    private javax.swing.JTextField txt_Student_Surname;
    // End of variables declaration//GEN-END:variables
}
