
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TENGAH
 */
public class Manage_All_Students extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form All_Students
     */
    public Manage_All_Students() {
        initComponents();
        show_students();
    }
public ArrayList<Students> userList(){
        ArrayList<Students> userList = new ArrayList<>();
         try{
            String query = "SELECT * FROM `students`";//fetching all data from the books database
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            rs= pst.executeQuery();
            Students students;
            while(rs.next()){
                students = new Students(rs.getString("Reg No"), rs.getString("Name"), rs.getString("Surname"),rs.getString("National_ID"),rs.getString("Gender"), rs.getString("Course"), rs.getString("Level"),rs.getString("Intake"), rs.getString("Intake_Year"), rs.getString("Status"));
                userList.add(students);
            }
         }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
         return userList;
    } 
    public void show_students(){
        ArrayList<Students> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable_Manage_All_Students.getModel();
        Object row[] = new Object[9];
       for(int i = 0; i<list.size(); i++){
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getSurname();
            row[2] = list.get(i).getCourse();
            row[3] = list.get(i).getGender();
            row[4] = list.get(i).getReg_Number();
            row[5] = list.get(i).getLevel();
            row[6] = list.get(i).getNationalID();
            row[7] = list.get(i).getIntake();
            row[8] = list.get(i).getIntake_Year();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Manage_All_Students = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel23_back = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_logged_book_search = new javax.swing.JTextField();
        for_back_only = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setPreferredSize(new java.awt.Dimension(307, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_books48.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Students Management Centre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(141, 133, 133));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Manage_All_Students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg Number", "Name", "Surname", "ID Number", "Gender", "Course", "Level", "Intake", "Intake Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Manage_All_Students.setGridColor(new java.awt.Color(63, 179, 175));
        jTable_Manage_All_Students.setSelectionBackground(new java.awt.Color(52, 73, 94));
        jScrollPane1.setViewportView(jTable_Manage_All_Students);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 420));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quick edit a student here.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 160, 20));

        jLabel23_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N
        jLabel23_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23_backMousePressed(evt);
            }
        });
        jPanel2.add(jLabel23_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 44, 40));

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search32.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 40, 50));

        jTextField1_logged_book_search.setBackground(new java.awt.Color(141, 133, 133));
        jTextField1_logged_book_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1_logged_book_search.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_logged_book_search.setToolTipText("Filter search  by Registration Number");
        jTextField1_logged_book_search.setBorder(null);
        jTextField1_logged_book_search.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1_logged_book_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_logged_book_searchActionPerformed(evt);
            }
        });
        jTextField1_logged_book_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_logged_book_searchKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1_logged_book_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 160, 30));

        for_back_only.setEditable(false);
        for_back_only.setBackground(new java.awt.Color(141, 133, 133));
        for_back_only.setForeground(new java.awt.Color(255, 255, 255));
        for_back_only.setText("            ");
        for_back_only.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        for_back_only.setCaretColor(new java.awt.Color(255, 255, 255));
        for_back_only.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        for_back_only.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_back_onlyActionPerformed(evt);
            }
        });
        jPanel2.add(for_back_only, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23_backMousePressed
        // TODO add your handling code here:
        new Students_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel23_backMousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        new Student_Update_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jTextField1_logged_book_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_logged_book_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_logged_book_searchActionPerformed

    private void jTextField1_logged_book_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_logged_book_searchKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1_logged_book_searchKeyReleased

    private void for_back_onlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_back_onlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_for_back_onlyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_All_Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField for_back_only;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23_back;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Manage_All_Students;
    private javax.swing.JTextField jTextField1_logged_book_search;
    // End of variables declaration//GEN-END:variables
}
