
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TENGAH
 */
public class Manage_All_Books extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form All_Books
     */
    public Manage_All_Books() {
        initComponents();
        show_user();
    }
    public ArrayList<User> userList(){
        ArrayList<User> userList = new ArrayList<>();
         try{
            String query = "SELECT * FROM `books`";//fetching all data from the books database
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            rs= pst.executeQuery();
            User user;
            while(rs.next()){
                user = new User(rs.getString("Accession_Number"), rs.getString("Name"), rs.getString("ISBN"),rs.getString("Author"),rs.getString("Edition"), rs.getString("Date_In"), rs.getString("Status"));
                userList.add(user);
            }
         }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
         return userList;
    } 
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable_Manage_All_Books.getModel();
        Object row[] = new Object[6];
       for(int i = 0; i<list.size(); i++){
            row[0] = list.get(i).getAccesion_Number();
            row[1] = list.get(i).getISBN();
            row[2] = list.get(i).getName();
            row[3] = list.get(i).getAuthor();
            row[4] = list.get(i).getEdition();
            row[5] = list.get(i).getDate_In();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_back = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Manage_All_Books = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_logged_book_search = new javax.swing.JTextField();
        for_back_only = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setPreferredSize(new java.awt.Dimension(307, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_books48.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Books Management Centre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 999, 73));

        jPanel2.setBackground(new java.awt.Color(141, 133, 133));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_back.setBackground(new java.awt.Color(141, 133, 133));
        jPanel_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_backMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_backLayout = new javax.swing.GroupLayout(jPanel_back);
        jPanel_back.setLayout(jPanel_backLayout);
        jPanel_backLayout.setHorizontalGroup(
            jPanel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel_backLayout.setVerticalGroup(
            jPanel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 409, -1, 50));

        jTable_Manage_All_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accession Number", "ISBN", "Name", "Author", "Edition", "Login Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Manage_All_Books.setGridColor(new java.awt.Color(63, 179, 175));
        jTable_Manage_All_Books.setInheritsPopupMenu(true);
        jTable_Manage_All_Books.setSelectionBackground(new java.awt.Color(52, 73, 94));
        jScrollPane1.setViewportView(jTable_Manage_All_Books);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 390));

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search32.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 40, 50));

        jTextField1_logged_book_search.setBackground(new java.awt.Color(141, 133, 133));
        jTextField1_logged_book_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1_logged_book_search.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_logged_book_search.setToolTipText("Filter search  by Accession Number");
        jTextField1_logged_book_search.setBorder(null);
        jTextField1_logged_book_search.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1_logged_book_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_logged_book_searchActionPerformed(evt);
            }
        });
        jTextField1_logged_book_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_logged_book_searchKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1_logged_book_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 160, 30));

        for_back_only.setEditable(false);
        for_back_only.setBackground(new java.awt.Color(141, 133, 133));
        for_back_only.setForeground(new java.awt.Color(255, 255, 255));
        for_back_only.setText("            ");
        for_back_only.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        for_back_only.setCaretColor(new java.awt.Color(255, 255, 255));
        for_back_only.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        for_back_only.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_back_onlyActionPerformed(evt);
            }
        });
        jPanel2.add(for_back_only, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 210, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quick edit a book here.");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 999, 469));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_backMousePressed
        // TODO add your handling code here:
        new Books_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel_backMousePressed

    private void jTextField1_logged_book_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_logged_book_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_logged_book_searchActionPerformed

    private void for_back_onlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_back_onlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_for_back_onlyActionPerformed

    private void jTextField1_logged_book_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_logged_book_searchKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1_logged_book_searchKeyReleased

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        new Book_Update_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_All_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_All_Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField for_back_only;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Manage_All_Books;
    private javax.swing.JTextField jTextField1_logged_book_search;
    // End of variables declaration//GEN-END:variables
}
