
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TENGAH
 */
public class Return_Book_window extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Return_Book_window
     */
    public Return_Book_window() {
        initComponents();
        txt_Book_ISBN_return.setEditable(false);
        txt_Book_Name_return.setEditable(false);
        txt_Book_Author_return.setEditable(false);
        txt_Book_Edition_return.setEditable(false);
        txt_Book_Borr_Condition_return.setEditable(false);
        txt_Book_Date_Borrowed_return.setEditable(false);
        txt_Book_Return_Date_return.setEditable(false);
        txt_Book_Days_spent_return.setEditable(false);
        Student_Search_Enable.setVisible(false);
        Book_Search_Enable.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_Book_ISBN_return = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_Book_Name_return = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Book_Author_return = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_Book_Edition_return = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txt_Book_Date_Borrowed_return = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txt_Book_Days_spent_return = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txt_Student_Surname_return = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txt_Student_Name_return = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txt_Student_Gender_return = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txt_Student_ID_return = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        txt_Return_student_search_by_Reg_Number = new javax.swing.JTextField();
        Student_search_button = new javax.swing.JLabel();
        Student_Search_Enable = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        txt_Book_Return_Date_return = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txt_Return_book_search_by_acc_number = new javax.swing.JTextField();
        Book_search_button = new javax.swing.JLabel();
        Book_Search_Enable = new javax.swing.JLabel();
        issue_book_button = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_Issue_Back_Button = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        txt_Book_Borr_Condition_return = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        stdc = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        stdl = new javax.swing.JTextField();
        Available = new javax.swing.JLabel();
        std_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));
        jPanel1.setPreferredSize(new java.awt.Dimension(843, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Book Window");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, 230, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_issue48.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, 70));

        jPanel2.setBackground(new java.awt.Color(141, 133, 133));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ISBN");

        txt_Book_ISBN_return.setEditable(false);
        txt_Book_ISBN_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_ISBN_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_ISBN_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN_return.setBorder(null);
        txt_Book_ISBN_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_ISBN_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_ISBN_return.setName(""); // NOI18N
        txt_Book_ISBN_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_ISBN_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_ISBN_returnActionPerformed(evt);
            }
        });
        txt_Book_ISBN_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_ISBN_returnKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        txt_Book_Name_return.setEditable(false);
        txt_Book_Name_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Name_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Name_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Name_return.setBorder(null);
        txt_Book_Name_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Name_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Name_return.setName(""); // NOI18N
        txt_Book_Name_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Name_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Name_returnActionPerformed(evt);
            }
        });
        txt_Book_Name_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Name_returnKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author");

        txt_Book_Author_return.setEditable(false);
        txt_Book_Author_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Author_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Author_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Author_return.setBorder(null);
        txt_Book_Author_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Author_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Author_return.setName(""); // NOI18N
        txt_Book_Author_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Author_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Author_returnActionPerformed(evt);
            }
        });
        txt_Book_Author_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Author_returnKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edition");

        txt_Book_Edition_return.setEditable(false);
        txt_Book_Edition_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Edition_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Edition_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Edition_return.setBorder(null);
        txt_Book_Edition_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Edition_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Edition_return.setName(""); // NOI18N
        txt_Book_Edition_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Edition_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Edition_returnActionPerformed(evt);
            }
        });
        txt_Book_Edition_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Edition_returnKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Borrowed Condition");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Borrowed");

        txt_Book_Date_Borrowed_return.setEditable(false);
        txt_Book_Date_Borrowed_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Date_Borrowed_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Date_Borrowed_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Date_Borrowed_return.setBorder(null);
        txt_Book_Date_Borrowed_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Date_Borrowed_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Date_Borrowed_return.setName(""); // NOI18N
        txt_Book_Date_Borrowed_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Date_Borrowed_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Date_Borrowed_returnActionPerformed(evt);
            }
        });
        txt_Book_Date_Borrowed_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Date_Borrowed_returnKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Days Spent");

        txt_Book_Days_spent_return.setEditable(false);
        txt_Book_Days_spent_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Days_spent_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Days_spent_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Days_spent_return.setBorder(null);
        txt_Book_Days_spent_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Days_spent_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Days_spent_return.setName(""); // NOI18N
        txt_Book_Days_spent_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Days_spent_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Days_spent_returnActionPerformed(evt);
            }
        });
        txt_Book_Days_spent_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Days_spent_returnKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Surname");

        txt_Student_Surname_return.setEditable(false);
        txt_Student_Surname_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Surname_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Surname_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Surname_return.setBorder(null);
        txt_Student_Surname_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Surname_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Surname_return.setName(""); // NOI18N
        txt_Student_Surname_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Surname_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_Surname_returnActionPerformed(evt);
            }
        });
        txt_Student_Surname_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_Surname_returnKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Name");

        txt_Student_Name_return.setEditable(false);
        txt_Student_Name_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Name_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Name_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Name_return.setBorder(null);
        txt_Student_Name_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Name_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Name_return.setName(""); // NOI18N
        txt_Student_Name_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Name_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_Name_returnActionPerformed(evt);
            }
        });
        txt_Student_Name_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_Name_returnKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");

        txt_Student_Gender_return.setEditable(false);
        txt_Student_Gender_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_Gender_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_Gender_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_Gender_return.setBorder(null);
        txt_Student_Gender_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_Gender_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_Gender_return.setName(""); // NOI18N
        txt_Student_Gender_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_Gender_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_Gender_returnActionPerformed(evt);
            }
        });
        txt_Student_Gender_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_Gender_returnKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID");

        txt_Student_ID_return.setEditable(false);
        txt_Student_ID_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Student_ID_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Student_ID_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Student_ID_return.setToolTipText("Book ISBN");
        txt_Student_ID_return.setBorder(null);
        txt_Student_ID_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Student_ID_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Student_ID_return.setName(""); // NOI18N
        txt_Student_ID_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Student_ID_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Student_ID_returnActionPerformed(evt);
            }
        });
        txt_Student_ID_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Student_ID_returnKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Course");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Level");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txt_Return_student_search_by_Reg_Number.setBackground(new java.awt.Color(141, 133, 133));
        txt_Return_student_search_by_Reg_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Return_student_search_by_Reg_Number.setForeground(new java.awt.Color(255, 255, 255));
        txt_Return_student_search_by_Reg_Number.setToolTipText("Enter student Reg number");
        txt_Return_student_search_by_Reg_Number.setBorder(null);
        txt_Return_student_search_by_Reg_Number.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Return_student_search_by_Reg_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Return_student_search_by_Reg_NumberActionPerformed(evt);
            }
        });
        txt_Return_student_search_by_Reg_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Return_student_search_by_Reg_NumberKeyReleased(evt);
            }
        });

        Student_search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search32.png"))); // NOI18N
        Student_search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Student_search_buttonMousePressed(evt);
            }
        });

        Student_Search_Enable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enable_tickC32.png"))); // NOI18N
        Student_Search_Enable.setToolTipText("Enable search");
        Student_Search_Enable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_Search_Enable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Student_Search_EnableMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Return Date");

        txt_Book_Return_Date_return.setEditable(false);
        txt_Book_Return_Date_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Return_Date_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Return_Date_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Return_Date_return.setBorder(null);
        txt_Book_Return_Date_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Return_Date_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Return_Date_return.setName(""); // NOI18N
        txt_Book_Return_Date_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Return_Date_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Return_Date_returnActionPerformed(evt);
            }
        });
        txt_Book_Return_Date_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Return_Date_returnKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Borrower Details here.");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Book Details here.");

        txt_Return_book_search_by_acc_number.setBackground(new java.awt.Color(141, 133, 133));
        txt_Return_book_search_by_acc_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Return_book_search_by_acc_number.setForeground(new java.awt.Color(255, 255, 255));
        txt_Return_book_search_by_acc_number.setToolTipText("Enter book accession number");
        txt_Return_book_search_by_acc_number.setBorder(null);
        txt_Return_book_search_by_acc_number.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Return_book_search_by_acc_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Return_book_search_by_acc_numberActionPerformed(evt);
            }
        });
        txt_Return_book_search_by_acc_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Return_book_search_by_acc_numberKeyReleased(evt);
            }
        });

        Book_search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search32.png"))); // NOI18N
        Book_search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Book_search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Book_search_buttonMousePressed(evt);
            }
        });

        Book_Search_Enable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enable_tickC32.png"))); // NOI18N
        Book_Search_Enable.setToolTipText("Enable search");
        Book_Search_Enable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Book_Search_Enable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Book_Search_EnableMousePressed(evt);
            }
        });

        issue_book_button.setBackground(new java.awt.Color(118, 150, 166));
        issue_book_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issue_book_button.setName(""); // NOI18N
        issue_book_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                issue_book_buttonMousePressed(evt);
            }
        });
        issue_book_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Return Book");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        issue_book_button.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 20));

        jLabel_Issue_Back_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N
        jLabel_Issue_Back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_Issue_Back_ButtonMousePressed(evt);
            }
        });

        txt_Book_Borr_Condition_return.setEditable(false);
        txt_Book_Borr_Condition_return.setBackground(new java.awt.Color(141, 133, 133));
        txt_Book_Borr_Condition_return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Book_Borr_Condition_return.setForeground(new java.awt.Color(255, 255, 255));
        txt_Book_Borr_Condition_return.setBorder(null);
        txt_Book_Borr_Condition_return.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Book_Borr_Condition_return.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Book_Borr_Condition_return.setName(""); // NOI18N
        txt_Book_Borr_Condition_return.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Book_Borr_Condition_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Book_Borr_Condition_returnActionPerformed(evt);
            }
        });
        txt_Book_Borr_Condition_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Book_Borr_Condition_returnKeyPressed(evt);
            }
        });

        stdc.setEditable(false);
        stdc.setBackground(new java.awt.Color(141, 133, 133));
        stdc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stdc.setForeground(new java.awt.Color(255, 255, 255));
        stdc.setBorder(null);
        stdc.setCaretColor(new java.awt.Color(255, 255, 255));
        stdc.setMargin(new java.awt.Insets(2, 2, 0, 2));
        stdc.setName(""); // NOI18N
        stdc.setSelectionColor(new java.awt.Color(102, 102, 102));
        stdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdcActionPerformed(evt);
            }
        });
        stdc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stdcKeyPressed(evt);
            }
        });

        stdl.setEditable(false);
        stdl.setBackground(new java.awt.Color(141, 133, 133));
        stdl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stdl.setForeground(new java.awt.Color(255, 255, 255));
        stdl.setBorder(null);
        stdl.setCaretColor(new java.awt.Color(255, 255, 255));
        stdl.setMargin(new java.awt.Insets(2, 2, 0, 2));
        stdl.setName(""); // NOI18N
        stdl.setSelectionColor(new java.awt.Color(102, 102, 102));
        stdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdlActionPerformed(evt);
            }
        });
        stdl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stdlKeyPressed(evt);
            }
        });

        Available.setForeground(new java.awt.Color(141, 133, 133));
        Available.setText("Available");

        std_status.setForeground(new java.awt.Color(141, 133, 133));
        std_status.setText("Null");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Date_Borrowed_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Edition_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Author_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Name_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_ISBN_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Return_Date_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Borr_Condition_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Days_spent_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Book_search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Return_book_search_by_acc_number, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Book_Search_Enable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Student_Gender_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Student_Name_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Student_Surname_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Student_search_button)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Return_student_search_by_Reg_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(Student_Search_Enable))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdl, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdc, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Student_ID_return, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(std_status, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(Available)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(issue_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400)
                .addComponent(jLabel_Issue_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Available)
                            .addComponent(issue_book_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Book_search_button)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Return_book_search_by_acc_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Book_Search_Enable)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Return_student_search_by_Reg_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Student_search_button)
                                    .addComponent(Student_Search_Enable))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Book_ISBN_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Book_Name_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Student_Name_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Student_Surname_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Author_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Student_Gender_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Edition_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Student_ID_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Book_Borr_Condition_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Book_Date_Borrowed_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Book_Return_Date_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(stdl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_Book_Days_spent_return, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(std_status)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Issue_Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Book_ISBN_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_ISBN_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBN_returnActionPerformed

    private void txt_Book_ISBN_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_ISBN_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_ISBN_returnKeyPressed

    private void txt_Book_Name_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Name_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Name_returnActionPerformed

    private void txt_Book_Name_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Name_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Name_returnKeyPressed

    private void txt_Book_Author_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Author_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Author_returnActionPerformed

    private void txt_Book_Author_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Author_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Author_returnKeyPressed

    private void txt_Book_Edition_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Edition_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Edition_returnActionPerformed

    private void txt_Book_Edition_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Edition_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Edition_returnKeyPressed

    private void txt_Book_Date_Borrowed_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Date_Borrowed_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Date_Borrowed_returnActionPerformed

    private void txt_Book_Date_Borrowed_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Date_Borrowed_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Date_Borrowed_returnKeyPressed

    private void txt_Book_Days_spent_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Days_spent_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Days_spent_returnActionPerformed

    private void txt_Book_Days_spent_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Days_spent_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Days_spent_returnKeyPressed

    private void txt_Student_Surname_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_Surname_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Surname_returnActionPerformed

    private void txt_Student_Surname_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_Surname_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Surname_returnKeyPressed

    private void txt_Student_Name_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_Name_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Name_returnActionPerformed

    private void txt_Student_Name_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_Name_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Name_returnKeyPressed

    private void txt_Student_Gender_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_Gender_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Gender_returnActionPerformed

    private void txt_Student_Gender_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_Gender_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_Gender_returnKeyPressed

    private void txt_Student_ID_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Student_ID_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_ID_returnActionPerformed

    private void txt_Student_ID_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Student_ID_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Student_ID_returnKeyPressed

    private void txt_Return_student_search_by_Reg_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Return_student_search_by_Reg_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Return_student_search_by_Reg_NumberActionPerformed

    private void txt_Return_student_search_by_Reg_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Return_student_search_by_Reg_NumberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Return_student_search_by_Reg_NumberKeyReleased

    private void Student_search_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_search_buttonMousePressed
        // TODO add your handling code here:
        if(txt_Return_student_search_by_Reg_Number.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Null value, can't find borrower!");
         }else{
        try {
            String query = "SELECT * FROM `issue_book` WHERE `Student_Reg_No` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_Return_student_search_by_Reg_Number.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txt_Return_student_search_by_Reg_Number.setEditable(false);
                Student_Search_Enable.setVisible(true);
                /*---------------------------------------------------*/
                String setStudent_name = rs.getString("Student_Name");
                txt_Student_Name_return.setText(setStudent_name);

                String setStudent_surname = rs.getString("Student_Surname");
                txt_Student_Surname_return.setText(setStudent_surname);

                String setStudent_gender = rs.getString("Student_Gender");
                txt_Student_Gender_return.setText(setStudent_gender);

                String setStudent_ID = rs.getString("Student_ID");
                txt_Student_ID_return.setText(setStudent_ID);

                String setStudent_Course = rs.getString("_Course");
                stdc.setText(setStudent_Course);

                String setStudent_level = rs.getString("_Level");
                stdl.setText(setStudent_level);
            } else {
                JOptionPane.showMessageDialog(this, "Borrower not found, check your syntax!");
                txt_Student_Name_return.setText("");
                txt_Student_Surname_return.setText("");
                txt_Student_Gender_return.setText("");
                txt_Student_ID_return.setText("");
                stdc.setText("");
                stdl.setText("");
                txt_Return_student_search_by_Reg_Number.setText("");
                /*-------------------------------------------*/
 /* txt_Student_Name.setEditable(false);
                txt_Student_Surname.setEditable(false);
                txt_Student_ID.setEditable(false);
                txt_Student_Gender.setEditable(false);
                txt_Student_Course.setEditable(false);
                txt_Student_Level.setEditable(false);
                txt_Student_Intake.setEditable(false);
                txt_Student_Intake_Year.setEditable(false);*/
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_Student_search_buttonMousePressed

    private void Student_Search_EnableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_Search_EnableMousePressed
        // TODO add your handling code here:
        txt_Return_student_search_by_Reg_Number.setEditable(true);
        Student_Search_Enable.setVisible(false);
        /*-------------------------------------*/
        txt_Student_Name_return.setText("");
        txt_Student_Surname_return.setText("");
        txt_Student_Gender_return.setText("");
        txt_Student_ID_return.setText("");
        stdc.setText("");
        stdl.setText("");
        txt_Return_student_search_by_Reg_Number.setText("");
        /*-----------------------------------*/
 /* txt_Book_Update_ISBN.setEditable(false);
        txt_Book_Update_Name.setEditable(false);
        txt_Book_Update_Author.setEditable(false);
        txt_Book_Update_Edition.setEditable(false);
        jLabel9_Book_Search_Enable.setVisible(false);
        -----------------------------------*/
    }//GEN-LAST:event_Student_Search_EnableMousePressed

    private void txt_Book_Return_Date_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Return_Date_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Return_Date_returnActionPerformed

    private void txt_Book_Return_Date_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Return_Date_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Return_Date_returnKeyPressed

    private void txt_Return_book_search_by_acc_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Return_book_search_by_acc_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Return_book_search_by_acc_numberActionPerformed

    private void txt_Return_book_search_by_acc_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Return_book_search_by_acc_numberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Return_book_search_by_acc_numberKeyReleased

    private void Book_search_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_search_buttonMousePressed
        // TODO add your handling code here:
         if(txt_Return_book_search_by_acc_number.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Null value, can't find book!");
         }else{
        try {
            String query = "SELECT * FROM `issue_book` WHERE `Book_Accession_Number` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_Return_book_search_by_acc_number.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                /*-------------------------------------------------*/
 /*txt_Book_ISBN_return.setEditable(true);
                txt_Book_Name_return.setEditable(true);
                txt_Book_Author_return.setEditable(true);
                txt_Book_Edition_return.setEditable(true);
                txt_Book_Borr_Condition_return.setEditable(true);
                txt_Book_Date_Borrowed_return.setEditable(true);
                txt_Book_Return_Date_return.setEditable(true);
                txt_Book_Days_spent_return.setEditable(true);
                */
 /*-------------------------------------------------*/
                txt_Return_book_search_by_acc_number.setEditable(false);
                Book_Search_Enable.setVisible(true);

                String setBook_ISBN = rs.getString("Book_ISBN");
                txt_Book_ISBN_return.setText(setBook_ISBN);

                String setBook_Name = rs.getString("Book_Name");
                txt_Book_Name_return.setText(setBook_Name);

                String setBook_Author = rs.getString("Book_Author");
                txt_Book_Author_return.setText(setBook_Author);

                String setBook_Edition = rs.getString("Book_Edition");
                txt_Book_Edition_return.setText(setBook_Edition);

                String setBook_Condition = rs.getString("Book_Condition");
                txt_Book_Borr_Condition_return.setText(setBook_Condition);

                String setBook_Date_Borrowed = rs.getString("Issue_Date");
                txt_Book_Date_Borrowed_return.setText(setBook_Date_Borrowed);

                String setBook_Return_Date = rs.getString("Return_Date");
                txt_Book_Return_Date_return.setText(setBook_Return_Date);

                String setBook_Days_Spent = rs.getString("Days_Spent");
                txt_Book_Days_spent_return.setText(setBook_Days_Spent);
                // txt_Date_Logged_In_Update.setText(setDate);

            } else {
                JOptionPane.showMessageDialog(this, "The book you are trying to access was not found!");
                /*-------------------------------------------------*/
                txt_Book_ISBN_return.setText("");
                txt_Book_Name_return.setText("");
                txt_Book_Author_return.setText("");
                txt_Book_Edition_return.setText("");
                txt_Book_Borr_Condition_return.setText("");
                txt_Book_Date_Borrowed_return.setText("");
                txt_Book_Return_Date_return.setText("");
                txt_Book_Days_spent_return.setText("");
                txt_Return_book_search_by_acc_number.setText("");
                /*-------------------------------------------------*/
                txt_Book_ISBN_return.setEditable(false);
                txt_Book_Name_return.setEditable(false);
                txt_Book_Author_return.setEditable(false);
                txt_Book_Edition_return.setEditable(false);
                txt_Book_Borr_Condition_return.setEditable(false);
                txt_Book_Date_Borrowed_return.setEditable(false);
                txt_Book_Return_Date_return.setEditable(false);
                txt_Book_Days_spent_return.setEditable(false);
                /*-------------------------------------------------*/
                //jDateChooser1_Update.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
         }
    }//GEN-LAST:event_Book_search_buttonMousePressed

    private void Book_Search_EnableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_Search_EnableMousePressed
        // TODO add your handling code here:
        txt_Return_book_search_by_acc_number.setEditable(true);
        Book_Search_Enable.setVisible(false);
        /*-------------------------------------*/
        txt_Book_ISBN_return.setText("");
        txt_Book_Name_return.setText("");
        txt_Book_Author_return.setText("");
        txt_Book_Edition_return.setText("");
        txt_Book_Borr_Condition_return.setText("");
        txt_Book_Date_Borrowed_return.setText("");
        txt_Book_Return_Date_return.setText("");
        txt_Book_Days_spent_return.setText("");
        txt_Return_book_search_by_acc_number.setText("");
        /*-----------------------------------*/
        //txt_Book_ISBN.setEditable(false);
        //txt_Book_Name.setEditable(false);
        //txt_Book_Author.setEditable(false);
        //txt_Book_Edition.setEditable(false);
        //jLabel9_Book_Search_Enable.setVisible(false);
        /*-----------------------------------*/
    }//GEN-LAST:event_Book_Search_EnableMousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MousePressed

    private void issue_book_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_book_buttonMousePressed
        // TODO add your handling code here:
        /* if ((txt_Signup_name.getText().trim().isEmpty()) && (txt_Signup_ID.getText().trim().isEmpty()) && (txt_Signup_code.getText().trim().isEmpty()) && (txt_signup_password.getText().trim().isEmpty()) && (txt_signup_confirm_password.getText().trim().isEmpty())) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No input data found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        } else if ((txt_Signup_name.getText().trim().isEmpty()) || (txt_Signup_ID.getText().trim().isEmpty()) || (txt_Signup_code.getText().trim().isEmpty()) || (txt_signup_password.getText().trim().isEmpty()) || (txt_signup_confirm_password.getText().trim().isEmpty())) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Empty fields found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        }*/
 /* try{
            String sql = "INSERT INTO `issue_book`() VALUES (?, ?, ?, ?, ?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(sql);

            pst.executeUpdate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Issue on students");
        }*/
        try {
            
            /*---BORROW BOOK PROCESS----------------------allowing for the book to be borrowed again-*/
            try {
                String query2 = "UPDATE `books` SET `Status` =? WHERE `Accession_Number` = ?";
                conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
                pst = conn.prepareStatement(query2);
                pst.setString(2, txt_Return_book_search_by_acc_number.getText());
                pst.setString(1, Available.getText());
                pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            /*-------------------------------process ends here--------------------------------------------*/
            /*---BORROW BOOK PROCESS----------------------allowing a student to be able to borrow a book again-*/
            try {
                String query2 = "UPDATE `students` SET `Status`= ? WHERE `Reg No` = ?";
                conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
                pst = conn.prepareStatement(query2);
                pst.setString(2, txt_Return_student_search_by_Reg_Number.getText());
                pst.setString(1, std_status.getText());
                pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            /*-------------------------------process ends here--------------------------------------------*/
            String query1 = "DELETE FROM `issue_book` WHERE `Book_Accession_Number` = ? and `Student_Reg_No` = ?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query1);
            pst.setString(2, txt_Return_student_search_by_Reg_Number.getText());
            pst.setString(1, txt_Return_book_search_by_acc_number.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Book Return Successfull");
            txt_Return_book_search_by_acc_number.setText("");
            txt_Book_ISBN_return.setText("");
            txt_Book_Name_return.setText("");
            txt_Book_Author_return.setText("");
            txt_Book_Edition_return.setText("");
            txt_Book_Borr_Condition_return.setText("");
            txt_Book_Date_Borrowed_return.setText("");
            txt_Book_Return_Date_return.setText("");
            txt_Book_Days_spent_return.setText("");
            /*----------------------------------------------------------------------*/
            txt_Return_student_search_by_Reg_Number.setText("");
            txt_Student_Name_return.setText("");
            txt_Student_Surname_return.setText("");
            txt_Student_Gender_return.setText("");
            txt_Student_ID_return.setText("");
            stdc.setText("");
            stdl.setText("");
            /*----------------------------------------------------------------------*/
            txt_Return_student_search_by_Reg_Number.setEditable(true);
            txt_Return_book_search_by_acc_number.setEditable(true);
            Book_Search_Enable.setVisible(false);
            Student_Search_Enable.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Process Failed");
        }

    }//GEN-LAST:event_issue_book_buttonMousePressed

    private void jLabel_Issue_Back_ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Issue_Back_ButtonMousePressed
        // TODO add your handling code here:
        new Books_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel_Issue_Back_ButtonMousePressed

    private void txt_Book_Borr_Condition_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Book_Borr_Condition_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Borr_Condition_returnActionPerformed

    private void txt_Book_Borr_Condition_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Book_Borr_Condition_returnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Book_Borr_Condition_returnKeyPressed

    private void stdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdcActionPerformed

    private void stdcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdcKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdcKeyPressed

    private void stdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdlActionPerformed

    private void stdlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdlKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdlKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_Book_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_Book_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Available;
    private javax.swing.JLabel Book_Search_Enable;
    private javax.swing.JLabel Book_search_button;
    private javax.swing.JLabel Student_Search_Enable;
    private javax.swing.JLabel Student_search_button;
    private javax.swing.JPanel issue_book_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Issue_Back_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel std_status;
    private javax.swing.JTextField stdc;
    private javax.swing.JTextField stdl;
    private javax.swing.JTextField txt_Book_Author_return;
    private javax.swing.JTextField txt_Book_Borr_Condition_return;
    private javax.swing.JTextField txt_Book_Date_Borrowed_return;
    private javax.swing.JTextField txt_Book_Days_spent_return;
    private javax.swing.JTextField txt_Book_Edition_return;
    private javax.swing.JTextField txt_Book_ISBN_return;
    private javax.swing.JTextField txt_Book_Name_return;
    private javax.swing.JTextField txt_Book_Return_Date_return;
    private javax.swing.JTextField txt_Return_book_search_by_acc_number;
    private javax.swing.JTextField txt_Return_student_search_by_Reg_Number;
    private javax.swing.JTextField txt_Student_Gender_return;
    private javax.swing.JTextField txt_Student_ID_return;
    private javax.swing.JTextField txt_Student_Name_return;
    private javax.swing.JTextField txt_Student_Surname_return;
    // End of variables declaration//GEN-END:variables
}
