
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TENGAH
 */
public class SignIn_window extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Admin_Log
     */
    public SignIn_window() {
        initComponents();
        // conn = Sql_Connect.Connectdb();
        this.jLabel7_noview.setVisible(false);
        jLabel1_forgot_password.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6_view = new javax.swing.JLabel();
        signin_button = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7_noview = new javax.swing.JLabel();
        jLabel1_forgot_password = new javax.swing.JLabel();
        jLabel2_create_account = new javax.swing.JLabel();
        txt_Signin_name = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 507));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 507));

        jPanel3.setBackground(new java.awt.Color(141, 133, 133));
        jPanel3.setMaximumSize(new java.awt.Dimension(900, 900));
        jPanel3.setPreferredSize(new java.awt.Dimension(1010, 427));
        jPanel3.setRequestFocusEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        txt_ID.setBackground(new java.awt.Color(141, 133, 133));
        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_ID.setToolTipText("Your ID Number");
        txt_ID.setBorder(null);
        txt_ID.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_ID.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_IDFocusLost(evt);
            }
        });
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        txt_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IDKeyPressed(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(141, 133, 133));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setToolTipText("Your Password");
        txt_password.setAlignmentX(0.0F);
        txt_password.setAlignmentY(0.0F);
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_password.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_password.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_password.setSelectionStart(2);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        jLabel6_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye32.png"))); // NOI18N
        jLabel6_view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6_viewMousePressed(evt);
            }
        });

        signin_button.setBackground(new java.awt.Color(118, 150, 166));
        signin_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signin_buttonMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sign In");

        javax.swing.GroupLayout signin_buttonLayout = new javax.swing.GroupLayout(signin_button);
        signin_button.setLayout(signin_buttonLayout);
        signin_buttonLayout.setHorizontalGroup(
            signin_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signin_buttonLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(64, 64, 64))
        );
        signin_buttonLayout.setVerticalGroup(
            signin_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signin_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7_noview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key 32.png"))); // NOI18N
        jLabel7_noview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7_noview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7_noviewMousePressed(evt);
            }
        });

        jLabel1_forgot_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_forgot_password.setText("Forgot password");
        jLabel1_forgot_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_forgot_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1_forgot_passwordMousePressed(evt);
            }
        });

        jLabel2_create_account.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_create_account.setText("Create an account");
        jLabel2_create_account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_create_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2_create_accountMousePressed(evt);
            }
        });

        txt_Signin_name.setBackground(new java.awt.Color(141, 133, 133));
        txt_Signin_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Signin_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Signin_name.setToolTipText("Your Username");
        txt_Signin_name.setBorder(null);
        txt_Signin_name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Signin_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Signin_name.setSelectionColor(new java.awt.Color(102, 102, 102));
        txt_Signin_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Signin_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Signin_nameFocusLost(evt);
            }
        });
        txt_Signin_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Signin_nameActionPerformed(evt);
            }
        });
        txt_Signin_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Signin_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Signin_nameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Signin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1_forgot_password)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2_create_account))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7_noview, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_view, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Signin_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7_noview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6_view, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_create_account, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_forgot_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(52, 73, 94));
        jPanel5.setPreferredSize(new java.awt.Dimension(843, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sign In Window");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 54));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/decision64.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 54));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7_noviewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7_noviewMousePressed
        // TODO add your handling code here:
        jLabel7_noview.setVisible(false);
        jLabel6_view.setVisible(true);
        txt_password.setEchoChar('*');
    }//GEN-LAST:event_jLabel7_noviewMousePressed

    private void signin_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_buttonMousePressed
        // TODO add your handling code here:
        if ((txt_Signin_name.getText().trim().isEmpty()) || (txt_ID.getText().trim().isEmpty()) || (txt_password.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Empty fields found, fill in.", "Warning", 2);
            //getToolkit().beep();
            //new Alert().setVisible(true);
            //JOptionPane.showMessageDialog(this, "No input data found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (((txt_Signin_name.getText().trim().isEmpty()) || (txt_ID.getText().trim().isEmpty()) || (txt_password.getText().trim().isEmpty()))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Empty fields found", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String query = "SELECT * FROM `librarian_signup` WHERE `name` = ? and `ID` = ? and `password` = ?";//fetching data from the same database
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_Signin_name.getText());
            pst.setString(2, txt_ID.getText());
            pst.setString(3, txt_password.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                dispose();
                new Home_window().setVisible(true);
                // JOptionPane.showMessageDialog(this, "That was correct");
            } else {
                JOptionPane.showMessageDialog(this, "Authentication Failed");
                // txt_Signin_name.setText("");
                // txt_ID.setText("");
                //txt_password.setText("");
                // jLabel1_forgot_password.setText("Forgot password?");
                jLabel1_forgot_password.setVisible(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_signin_buttonMousePressed

    private void jLabel6_viewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6_viewMousePressed
        // TODO add your handling code here:
        jLabel6_view.setVisible(false);
        jLabel7_noview.setVisible(true);
        txt_password.setEchoChar((char) 0);

    }//GEN-LAST:event_jLabel6_viewMousePressed

    private void txt_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isISOControl(c) || Character.isWhitespace(c)) {
            txt_ID.setEditable(true);
        } else {
            txt_ID.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_IDKeyPressed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isISOControl(c) || Character.isLowerCase(c) || Character.isUpperCase(c)) {
            txt_password.setEditable(true);
        } else {
            txt_password.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_Signin_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Signin_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signin_nameActionPerformed

    private void txt_Signin_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Signin_nameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signin_nameKeyPressed

    private void jLabel1_forgot_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_forgot_passwordMousePressed
        // TODO add your handling code here:
        new Recover_my_account_window().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1_forgot_passwordMousePressed

    private void txt_Signin_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Signin_nameKeyReleased
        // TODO add your handling code here:
        /*String My_Pattern = "{0-10}";
        Pattern patt = Pattern.compile(My_Pattern);
        Matcher match = patt.matcher(txt_Signin_name.getText());
        if(!match.find()){
            getToolkit().beep();
        }*/
    }//GEN-LAST:event_txt_Signin_nameKeyReleased

    private void jLabel2_create_accountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_create_accountMousePressed
        // TODO add your handling code here:
        new Confirmation_Centre().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2_create_accountMousePressed

    private void txt_Signin_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Signin_nameFocusGained

    }//GEN-LAST:event_txt_Signin_nameFocusGained

    private void txt_Signin_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Signin_nameFocusLost

    }//GEN-LAST:event_txt_Signin_nameFocusLost

    private void txt_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_IDFocusGained


    }//GEN-LAST:event_txt_IDFocusGained

    private void txt_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_IDFocusLost

    }//GEN-LAST:event_txt_IDFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel1_forgot_password;
    private javax.swing.JLabel jLabel2_create_account;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_view;
    private javax.swing.JLabel jLabel7_noview;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel signin_button;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Signin_name;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
