
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TENGAH
 */
public class SignUp_window extends javax.swing.JFrame {
        Connection conn= null;
        PreparedStatement pst= null;
        ResultSet rs= null; 
    /**
     * Creates new form SignUp_window
     */
    public SignUp_window() {
        initComponents();
        conn = Sql_Connect.Connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_signup_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_signup_confirm_password = new javax.swing.JPasswordField();
        signin_next_button = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txt_Signup_name = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_Signup_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(52, 73, 94));
        jPanel5.setPreferredSize(new java.awt.Dimension(843, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sign Up Window");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 54));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/up48.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 54));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jPanel1.setBackground(new java.awt.Color(141, 133, 133));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back64.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel23MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        txt_signup_password.setBackground(new java.awt.Color(141, 133, 133));
        txt_signup_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_signup_password.setToolTipText("Your preferred password");
        txt_signup_password.setAlignmentX(0.0F);
        txt_signup_password.setAlignmentY(0.0F);
        txt_signup_password.setBorder(null);
        txt_signup_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_signup_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_signup_password.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_signup_password.setSelectionStart(2);
        txt_signup_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_signup_passwordKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");

        txt_signup_confirm_password.setBackground(new java.awt.Color(141, 133, 133));
        txt_signup_confirm_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_signup_confirm_password.setToolTipText("Confirm your password");
        txt_signup_confirm_password.setAlignmentX(0.0F);
        txt_signup_confirm_password.setAlignmentY(0.0F);
        txt_signup_confirm_password.setBorder(null);
        txt_signup_confirm_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_signup_confirm_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_signup_confirm_password.setPreferredSize(new java.awt.Dimension(6, 23));
        txt_signup_confirm_password.setSelectionStart(2);
        txt_signup_confirm_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_signup_confirm_passwordKeyPressed(evt);
            }
        });

        signin_next_button.setBackground(new java.awt.Color(118, 150, 166));
        signin_next_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signin_next_buttonMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Finish");

        javax.swing.GroupLayout signin_next_buttonLayout = new javax.swing.GroupLayout(signin_next_button);
        signin_next_button.setLayout(signin_next_buttonLayout);
        signin_next_buttonLayout.setHorizontalGroup(
            signin_next_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signin_next_buttonLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        signin_next_buttonLayout.setVerticalGroup(
            signin_next_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signin_next_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_Signup_name.setBackground(new java.awt.Color(141, 133, 133));
        txt_Signup_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Signup_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Signup_name.setToolTipText("Your Name");
        txt_Signup_name.setBorder(null);
        txt_Signup_name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Signup_name.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Signup_name.setName(""); // NOI18N
        txt_Signup_name.setSelectedTextColor(new java.awt.Color(102, 0, 255));
        txt_Signup_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Signup_nameActionPerformed(evt);
            }
        });
        txt_Signup_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Signup_nameKeyPressed(evt);
            }
        });

        txt_Surname.setBackground(new java.awt.Color(141, 133, 133));
        txt_Surname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Surname.setForeground(new java.awt.Color(255, 255, 255));
        txt_Surname.setToolTipText("Your Surname");
        txt_Surname.setBorder(null);
        txt_Surname.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Surname.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Surname.setName(""); // NOI18N
        txt_Surname.setSelectedTextColor(new java.awt.Color(102, 0, 255));
        txt_Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SurnameActionPerformed(evt);
            }
        });
        txt_Surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SurnameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Surname");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("National ID");

        txt_Signup_ID.setBackground(new java.awt.Color(141, 133, 133));
        txt_Signup_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Signup_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_Signup_ID.setToolTipText("Your National ID");
        txt_Signup_ID.setBorder(null);
        txt_Signup_ID.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Signup_ID.setMargin(new java.awt.Insets(2, 2, 0, 2));
        txt_Signup_ID.setName(""); // NOI18N
        txt_Signup_ID.setSelectedTextColor(new java.awt.Color(102, 0, 255));
        txt_Signup_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Signup_IDActionPerformed(evt);
            }
        });
        txt_Signup_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Signup_IDKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signin_next_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(48, 48, 48)
                                .addComponent(txt_signup_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txt_signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Signup_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Signup_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_signup_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(signin_next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1000, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signin_next_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_next_buttonMousePressed
        // TODO add your handling code here:  
       if ((txt_Signup_name.getText().trim().isEmpty()) || (txt_Signup_ID.getText().trim().isEmpty()) || (txt_signup_password.getText().trim().isEmpty()) || (txt_signup_confirm_password.getText().trim().isEmpty())) {
           // getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Empty fields found, fill in.", "Error?", JOptionPane.WARNING_MESSAGE);
            return;
        } 
          if (txt_signup_password.getText().equals(txt_signup_confirm_password.getText())) {
            //JOptionPane.showMessageDialog(null,"Password match,Saved");
        try{
            String query = "INSERT INTO `librarian_signup`(`name`,`Surname` , `ID`, `password`, `confirm password`) VALUES (?, ?, ? ,? ,?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/libot", "root", "tinotenda");
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_Signup_name.getText());
            pst.setString(2, txt_Surname.getText());
            pst.setString(3, txt_Signup_ID.getText());
            pst.setString(4, txt_signup_password.getText());
            pst.setString(5, txt_signup_confirm_password.getText());
            pst.executeUpdate();
            txt_Signup_name.setText("");
            txt_Surname.setText("");
            txt_Signup_ID.setText("");
            txt_signup_password.setText("");
            txt_signup_confirm_password.setText("");
            JOptionPane.showMessageDialog(this, "Section Completed Successfully");
            new Confirmation_Centre().setVisible(true);
        dispose();
        }catch(Exception ex){
        }
          }else{
              getToolkit().beep();
              new Alert_1().setVisible(true);
              //JOptionPane.showMessageDialog(this, "Passwords do not match", "Error?", JOptionPane.ERROR_MESSAGE);
          }
    }//GEN-LAST:event_signin_next_buttonMousePressed
    
    
    private void txt_signup_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_signup_passwordKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if(Character.isLetterOrDigit(c)|| Character.isISOControl(c) || Character.isLowerCase(c) || Character.isUpperCase(c) || Character.isDefined(c)){
          txt_signup_password.setEditable(true);  
        }else{
            txt_signup_password.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_signup_passwordKeyPressed

    private void txt_signup_confirm_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_signup_confirm_passwordKeyPressed
        // TODO add your handling code here:
         Character c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c) || Character.isLowerCase(c) || Character.isUpperCase(c)){
          txt_signup_confirm_password.setEditable(true);  
        }else{
            txt_signup_confirm_password.setEditable(false);
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_signup_confirm_passwordKeyPressed

    private void txt_Signup_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Signup_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signup_nameActionPerformed

    private void txt_Signup_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Signup_nameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signup_nameKeyPressed

    private void txt_SurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SurnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SurnameKeyPressed

    private void txt_SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SurnameActionPerformed

    private void txt_Signup_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Signup_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signup_IDActionPerformed

    private void txt_Signup_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Signup_IDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Signup_IDKeyPressed

    private void jLabel23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MousePressed
        // TODO add your handling code here:
        new Confirmation_Centre().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel23MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel signin_next_button;
    private javax.swing.JTextField txt_Signup_ID;
    private javax.swing.JTextField txt_Signup_name;
    private javax.swing.JTextField txt_Surname;
    private javax.swing.JPasswordField txt_signup_confirm_password;
    private javax.swing.JPasswordField txt_signup_password;
    // End of variables declaration//GEN-END:variables
}
